### ISSUE TITLE
Making WordPress OOP

### ISSUE THREAD

**Issue by szepeviktor** [TypistTech/wp-contained-hook#33]
Hello @TangRufus !

I see you develop OOP interfaces/tools for WordPress :)

This is my try on using `global $wpdb;` the OOP way: https://gist.github.com/szepeviktor/ddb1bfd12d93accd318cc081637956ec

Comments welcome.

**Comment by TangRufus** [comment]
Interesting idea. Let me know when your package is released.

Hope these links will help you:
- https://scotty-t.com/2017/03/28/performance-is-a-problem/
- https://github.com/drewjbartlett/wordpress-eloquent
- https://github.com/tareq1988/wp-eloquent

If you like wp-contained-hook, I have some more repos at https://github.com/typisttech

**Comment by TangRufus** [comment]
Also:
- https://github.com/anthonybudd/WP_Model
- https://github.com/BerlinDB

**Comment by szepeviktor** [comment]
Thank you.

**Comment by szepeviktor** [comment]
@TangRufus After a deep look WP_Model is so poorly written, please consider not to advertise it.

@BerlinDB is a **big** yes 👍

**Comment by TangRufus** [comment]
I would agree that if I were implementing WP_Model I would use a different implementation. Can you elaborate more about it?

---

I don't mind this issue becomes _off-topic_ (not related to wp-contained-hook). Your insight will be beneficial to developers.

**Comment by szepeviktor** [comment]
> But its API is awesome. Can you elaborate more about it?

Yes, I agree, it is a good idea.
The problem is with the execution. [Undefined method](https://github.com/anthonybudd/WP_Model/blob/master/src/WP_Model.php#L545), very strange coding style, unfinished methods, surprising methods (newWithoutConstructor). I do not dare to use it.
