### ISSUE TITLE
A very similar Project (WP_DICH)

### ISSUE THREAD

**Issue by pablo-sg-pacheco** [TypistTech/wp-contained-hook#47]
Hello,
I don't know if creating an issue is the best option here, but I just wanted to say I created a very similar project called WP_DICH, which also uses a Dependency Injection Container for WordPress Hooks.
https://github.com/thanks-to-it/wp-dich

I was just impressed I had almost the same idea!
I'm sorry if I'm disturbing or something. That was not the intention.

Congrats!

**Comment by TangRufus** [comment]
thanks-to-it/wp-dich looks awesome!

[`WP_DICH::need_to_remove`](https://github.com/thanks-to-it/wp-dich/blob/02d12dd6d622eaee9a76c2376c3dedf33f7f2fb9/src/class-wp-dich.php#L148) is something I never thought of.

**Comment by pablo-sg-pacheco** [comment]
Thanks!

It's because I decided to create a `remove_filter()` and `remove_action()` functions too.
So `need_to_remove` knows if the hook can be called or not depending on if it was removed or not.
