### ISSUE TITLE
Failing to work together with imposter-plugin

### ISSUE THREAD

**Issue by h4r1m4u** [TypistTech/wp-contained-hook#49]
Hi Rufus, 

I would love to bring this package into my project, but I am running into an issue when using it together with Imposter Plugin. During `composer require` I get the following error message:

```
Installation failed, reverting ./composer.json and ./composer.lock to their original content.

[RuntimeException]
File does not exist at path .../vendor/psr/container-implementation/composer.json
```

Steps to reproduce:

1. Start a new project with `composer init`.
2. Add the Imposter configuration in `composer.json` as per the instructions:
```
"extra": {
    "imposter": {
        "namespace": "My\\App\\Vendor"
    }
}
```
3. Install Imposter Plugin with `composer require typisttech/imposter-plugin`.
4. Install WP Contained Hook and League Container with `composer require typisttech/wp-contained-hook league/container`.

The last step throws the exception I mention above. 

Would you have any suggestions on how to resolve this? 

Thank you very much in advance. I really appreciate your help and all the packages you make available.

**Comment by tangrufus** [comment]
Virtual packages are not supported by imposter. See: https://github.com/TypistTech/imposter-plugin#known-issues

Use `extra.imposter.excludes` to ignore virtual packages. See: https://github.com/TypistTech/imposter-plugin#install

**Comment by h4r1m4u** [comment]
Thanks for the response, I appreciate it. 

I am confused, though, as neither Sunny nor WP Cloudflare Guard, which I checked for reference, use the `extra.imposter.excludes` declaration and both of those projects use both the League Container and the WP Contained Hook package.

**Comment by tangrufus** [comment]
Probably because they are on very old versions of imposter.
I haven't updated those 2 plugins in a long time.
